### ISSUE TITLE
Equations not rendering?

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystatstemplate#9]
See https://easystats.github.io/insight/reference/get_variance.html

Not sure, I _thought_ this was different before.
![image](https://github.com/easystats/easystatstemplate/assets/26301769/88823a3d-1926-4178-b2fd-465a7be1593a)

**Comment by IndrajeetPatil** [comment]
My guess is that this is an artefact of us not using the correct HTML equation, where relevant.

You can see how these two items are rendered, one correctly (since it specifies the correct HTML equation), the other incorrectly (since it doesn't):

```
#' - **Gaussian:** For Gaussian models, it is
#'   \ifelse{html}{\out{&sigma;<sup>2</sup>}}{\eqn{\sigma^2}} (i.e. `sigma(model)^2`).
#'
#' - **Bernoulli:** For models with binary outcome, it is \eqn{\pi^2 / 3} for
#'   logit-link, `1` for probit-link, and \eqn{\pi^2 / 6} for cloglog-links.
```

<img width="797" alt="Screenshot 2024-07-17 at 22 09 17" src="https://github.com/user-attachments/assets/d026d5c6-a129-4152-86b2-1b40e65cd536">
